PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vae: <https://w3id.org/def/vaeontology#>
PREFIX : <https://w3id.org/def/vaeontology_osman_dInverno#>

SELECT ?taxonomyStatement ?ta ?t ?rn ?rimp ?cp ?cpimp ?cc ?ccimp
WHERE {
  ?taxonomyStatement vae:expressesProperty ?ta .
  ?ta rdf:type vae:TaxonomyAlignment.
  ?ta rdf:value ?t .
  ?taxonomyStatement vae:hasRootNode ?rn .
  ?rn vae:expressesProperty ?ri .
  ?ri rdf:type vae:NodeImportance.
  ?ri vae:importanceValue ?rimp .
  ?taxonomyStatement vae:hasConceptNode ?cp .
  ?cp vae:expressesProperty ?cpi .
  ?cpi rdf:type vae:NodeImportance .
  ?cpi vae:importanceValue ?cpimp .
  ?cp vae:directlyGeneralizesNode ?cc .
  ?cc vae:expressesProperty ?cci .
  ?cci rdf:type vae:NodeImportance .
  ?cci vae:importanceValue ?ccimp .
}
ORDER BY ?taxonomyStatement ?rn ?cp
